[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dicepool = "2RrkEbo9XkFAgqtz5wL3xDgj3x9o6SiSw6meA9CjManb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
